apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployment.yaml
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: uptime-kuma
      name: uptime-kuma
    spec:
      ports:
        - name: "3003"
          port: 3003
          targetPort: 3001
      selector:
        io.kompose.service: uptime_kuma
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployment.yaml
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: uptime-kuma
      name: uptime-kuma
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: uptime-kuma
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o deployment.yaml
            kompose.version: 1.24.0 (4a2a0458)
          creationTimestamp: null
          labels:
            io.kompose.service: uptime-kuma
        spec:
          containers:
            - env:
                - name: PGID
                  value: "999"
                - name: PUID
                  value: "0"
                - name: TZ
                  value: America/Chicago
              image: louislam/uptime-kuma:1
              name: uptime-kuma
              ports:
                - containerPort: 3001
              resources: {}
              volumeMounts:
                - mountPath: /app/data
                  name: uptime-kuma-data
                - mountPath: /var/run/docker.sock
                  name: uptime-kuma-claim1
                  readOnly: true
          restartPolicy: Always
          volumes:
            - name: uptime-kuma-data
              persistentVolumeClaim:
                claimName: uptime-kuma-data
            - name: uptime-kuma-claim1
              persistentVolumeClaim:
                claimName: uptime-kuma-claim1
                readOnly: true
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: uptime-kuma-data
      name: uptime-kuma-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: uptime-kuma-claim1
      name: uptime-kuma-claim1
    spec:
      accessModes:
        - ReadOnlyMany
      resources:
        requests:
          storage: 100Mi
    status: {}
kind: List
metadata: {}

