---
- name: Ping a host
  hosts: all
  gather_facts: false

  tasks:
  - name: Ping the host
    ping:

  - name: Echo hostname of server
    ansible.builtin.shell: hostname
    register: hostname

  - name: Print hostname
    debug:
      msg: "Hostname is {{ hostname.stdout }}"