---
- name: Production Server Setup
  hosts: all
  roles:
    ###
    ### Requirements
    ###
    - role: homelab-users
      tags:
        - homelab-users
        - homelab
    - role: geerlingguy.docker
      when: ansible_architecture == "x86_64"
      tags:
        - docker
        - skip_ansible_lint
    - role: geerlingguy.docker
      tags:
        - docker
        - skip_ansible_lint

    # - role: geerlingguy.docker_arm
    #   when: ansible_architecture == "aarch64"
    #   tags:
    #     - docker_arm
    #     - skip_ansible_lint

    ##
    ## Homelab Roles
    ##
    - role: homelab-general
      become: true
      tags:
        - homelab-general
        - homelab
    - role: homelab-docker
      tags:
        - homelab-docker
        - homelab
