---
# roles/amcrest-sync/tasks/main.yml

- name: Check if Git repository exists
  stat:
    path: /opt/amcrest_sync/.git
  register: git_repo

- name: Clone Git repository
  git:
    repo: "https://github.com/pypeaday/amcrest_sync.git"
    dest: /opt/amcrest_sync
  become: true
  when: git_repo.stat.exists == False

- name: Check if Docker image exists
  command: docker images -q amcrest_sync:latest
  register: docker_image
  ignore_errors: true

- name: Build Docker image
  command: docker build -t amcrest_sync:latest .
  args:
    chdir: /opt/amcrest_sync/
  become: true
  when: docker_image.stdout == ""

- name: Schedule cron job to run Docker container
  cron:
    name: "Sync Amcrest Cameras"
    minute: "*/5"
    job: "docker run --rm amcrest_sync:latest"
  become: true
