apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployment.yaml
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: onedev
      name: onedev
    spec:
      ports:
        - name: "6610"
          port: 6610
          targetPort: 6610
        - name: "6611"
          port: 6611
          targetPort: 6611
      selector:
        io.kompose.service: onedev
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o deployment.yaml
        kompose.version: 1.24.0 (4a2a0458)
      creationTimestamp: null
      labels:
        io.kompose.service: onedev
      name: onedev
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: onedev
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o deployment.yaml
            kompose.version: 1.24.0 (4a2a0458)
          creationTimestamp: null
          labels:
            io.kompose.service: onedev
        spec:
          containers:
            - image: 1dev/server
              name: onedev
              ports:
                - containerPort: 6610
                - containerPort: 6611
              resources: {}
              volumeMounts:
                - mountPath: /var/run/docker.sock
                  name: onedev-claim0
                - mountPath: /opt/onedev
                  name: onedev
          restartPolicy: Always
          volumes:
            - name: onedev-claim0
              persistentVolumeClaim:
                claimName: onedev-claim0
            - name: onedev
              persistentVolumeClaim:
                claimName: onedev
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: onedev-claim0
      name: onedev-claim0
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: onedev
      name: onedev
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
kind: List
metadata: {}

