---
# enable or disable the application
vocal_remover_app_enabled: false
vocal_remover_app_available_externally: false

# directories
vocal_remover_app_data_directory: "{{ docker_home }}/vocal_remover_app"

# uid / gid
vocal_remover_app_user_id: "0"
vocal_remover_app_group_id: "0"

# network
vocal_remover_app_hostname: "vocal-remover-app"
vocal_remover_app_port: "8001"

# docker
vocal_remover_app_container_name: "vocal-remover-app"
vocal_remover_app_image_name: "pypeaday/vocal-remover-app"
vocal_remover_app_image_version: "latest"

# specs
# need a lot of memory for the model
vocal_remover_app_memory: "8g"


vocal_remover_app_domain: "{{ homelab_domain }}"
vocal_remover_app_nc_password: supersecret
vocal_remover_app_nc_target: 'Olivet Bible/Worship/Under Review'
vocal_remover_app_nc_instrumentals_only_target: 'Olivet Bible/Worship/Olivet Bible Instrumental Splits'
vocal_remover_app_nc_user: "user"
vocal_remover_app_nc_url: "https://nextcloud.{{ homelab_domain }}.com/remote.php/dav/files/{{ vocal_remover_app_nc_user }}"
vocal_remover_app_reroute_url: "https://nextcloud.{{ homelab_domain }}.com/apps/files/?dir=/Olivet%20Bible/Worship/Under%20Review&fileid=946578"
