---
- name: Start Stirlingtools
  block:
    - name: Create Stirlingtools Directories
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ homelab_user }}"
        group: "{{ homelab_group_name }}"
        mode: u=rwX,g=rwX,o=rX
      with_items:
        - "{{ stirlingtools_data_directory }}"

    - name: Stirlingtools Docker Container
      community.docker.docker_container:
        name: stirlingtools
        image: frooodle/s-pdf:latest
        pull: true
        volumes:
          - "{{ stirlingtools_data_directory }}/trainingData:/usr/share/tessdata" # Required for extra OCR languages
          - "{{ stirlingtools_data_directory }}/extraConfigs:/configs"
    #      - ./customFiles:/customFiles/
    #      - ./logs:/logs/
        ports:
          - "{{ stirlingtools_port_http }}:8080"
        env:
          TZ: "{{ homelab_timezone }}"
          PUID: "{{ stirlingtools_user_id }}"
          PGID: "{{ stirlingtools_group_id }}"
          DOCKER_ENABLE_SECURITY: "false"
          INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "false"
          LANGS: en_US
        restart_policy: unless-stopped
        memory: "{{ stirlingtools_memory }}"
        labels:
          traefik.enable: "{{ stirlingtools_available_externally | string }}"
          traefik.http.routers.stirlingtools.rule: "Host(`{{ stirlingtools_hostname }}.{{ homelab_domain }}`)"
          traefik.http.routers.stirlingtools.tls.certresolver: "letsencrypt"
          traefik.http.routers.stirlingtools.tls.domains[0].main: "{{ homelab_domain }}"
          traefik.http.routers.stirlingtools.tls.domains[0].sans: "*.{{ homelab_domain }}"
          traefik.http.services.stirlingtools.loadbalancer.server.port: "8080"
          traefik.http.routers.stirlingtools.middlewares: "default-whitelist@file"
  when: stirlingtools_enabled is true

- name: Stop Stirlingtools
  block:
    - name: Stop Stirlingtools
      community.docker.docker_container:
        name: stirlingtools
        state: absent
  when: stirlingtools_enabled is false
