---
immich_memes_enabled: false
immich_memes_available_externally: false

# secrets
immich_memes_database_username: postgres
immich_memes_database_password: password
immich_memes_database_port: "5432"

# data directory
immich_memes_data_directory: "{{ docker_home }}/immich-memes"
immich_memes_external_library: "/mnt/photos"

# network
immich_memes_network_name: "immich-network"
immich_memes_port: "2284"
immich_memes_hostname: "memes"

# docker
immich_memes_container_name: "immich-memes"
immich_memes_image_name: "ghcr.io/immich-app/immich-server"
immich_memes_machine_learning_image_name: ghcr.io/immich-app/immich-machine-learning
immich_memes_image_version: "release"
immich_memes_user_id: "1000"
immich_memes_group_id: "1000"

# database
immich_memes_database_image: docker.io/tensorchord/pgvecto-rs
immich_memes_database_tag: pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0

immich_memes_redis_image: docker.io/redis
immich_memes_redis_tag: 6.2-alpine@sha256:2d1463258f2764328496376f5d965f20c6a67f66ea2b06dc42af351f75248792

# Example tag: ${immich_memes_VERSION:-release}-cuda
immich_memes_machine_learning_image_tag: "{{ immich_image_version }}"

# specs
immich_memes_memory: 4G

# immich
immich_memes_jwt_secret: "verylongandsecrettext"
immich_memes_enable_mapbox: "false"
immich_memes_mapbox_key: ""
immich_memes_upload_location: "./library"
immich_memes_public_login_page_message: "Welcome to Paradise!"
