apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.24.0 (4a2a0458)
  creationTimestamp: null
  labels:
    io.kompose.service: uptime-kuma
  name: uptime-kuma
spec:
  ports:
    - name: "3003"
      port: 3003
      targetPort: 3001
  selector:
    io.kompose.service: uptime_kuma
status:
  loadBalancer: {}
