---
manyfold_enabled: false
manyfold_available_externally: false

# secrets
manyfold_secret_key_base: a_nice_long_random_string
manyfold_database_password: password

# data directory
manyfold_data_directory: "{{ docker_home }}/manyfold"

# network
manyfold_port: "3214"
manyfold_hostname: "manyfold"

# docker
manyfold_container_name: "manyfold"
manyfold_image_name: "ghcr.io/manyfold3d/manyfold"
manyfold_image_version: "latest"
manyfold_user_id: "1000"
manyfold_group_id: "1000"

# specs
manyfold_memory: 2G
