---
- name: Start Manyfold
  block:
    - name: Create Manyfold Data Directory
      become: true
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ homelab_user }}"
        group: "{{ homelab_group_name }}"
        mode: u=rwX,g=rwX,o=rX
      with_items:
        - "{{ manyfold_data_directory }}"
        - "{{ manyfold_data_directory }}/db"
        - "{{ manyfold_data_directory }}/libraries"
    - name: Manyfold Postgres Docker Container
      community.docker.docker_container:
        name: "manyfold-postgres"
        image: "postgres:15"
        pull: true
        volumes:
          - "{{ manyfold_data_directory }}/db:/var/lib/postgresql/data:rw"
        env:
          POSTGRES_USER: manyfold
          POSTGRES_PASSWORD: "{{ manyfold_database_password }}"
    - name: Manyfold Redis Docker Container
      community.docker.docker_container:
        name: "manyfold-redis"
        image: "redis:7"
        pull: true
    - name: Manyfold Docker Container
      community.docker.docker_container:
        name: "manyfold"
        image: "{{ manyfold_image_name }}:{{ manyfold_image_version }}"
        pull: true
        ports:
          - "{{ manyfold_port }}:3214"
        volumes:
          - "{{ manyfold_data_directory }}/libraries:/libraries:rw"
        env:
          TZ: "{{ homelab_timezone }}"
          PUID: "{{ manyfold_user_id }}"
          PGID: "{{ manyfold_group_id }}"
          REDIS_URL: redis://redis:6379/1
          DATABASE_ADAPTER: postgresql # mysql2 or sqlite3 are also supported
          DATABASE_HOST: postgres
          DATABASE_NAME: manyfold # or the path to the database file if using sqlite3
          DATABASE_USER: manyfold
          DATABASE_PASSWORD: "{{ manyfold_database_password }}"
          SECRET_KEY_BASE: "{{ manyfold_secret_key_base }}"
        restart_policy: unless-stopped
        memory: "{{ manyfold_memory }}"
        labels:
          traefik.enable: "{{ manyfold_available_externally | string }}"
          traefik.http.routers.manyfold.rule: Host(`{{ manyfold_hostname }}.{{ homelab_domain }}`)
          traefik.http.routers.manyfold.tls.certresolver: letsencrypt
          traefik.http.routers.manyfold.tls.domains[0].main: "{{ homelab_domain }}"
          traefik.http.routers.manyfold.tls.domains[0].sans: "*.{{ homelab_domain }}"
          traefik.http.routers.manyfold.middlewares: default-whitelist@file
          traefik.http.services.manyfold.loadbalancer.server.port: "3214"
        links:
          - manyfold-postgres:postgres
          - manyfold-redis:redis
  when: manyfold_enabled is true
- name: Stop manyfold
  block:
    - name: Stop manyfold
      community.docker.docker_container:
        name: "manyfold"
        state: absent
    - name: Stop manyfold-postgres
      community.docker.docker_container:
        name: "manyfold-postgres"
        state: absent
    - name: Stop manyfold-redis
      community.docker.docker_container:
        name: "manyfold-redis"
        state: absent
  when: manyfold_enabled is false
