# https://stirlingtools.com/docs/Getting%20started/Installation/Docker/Docker%20Install
---
stirlingtools_enabled: false
stirlingtools_available_externally: false

# directories
stirlingtools_data_directory: "{{ docker_home }}/stirlingtools"

# uid / gid
stirlingtools_user_id: "0"
stirlingtools_group_id: "0"

# error logging
stirlingtools_log_level: "error"

# network
stirlingtools_port_http: "8010"

stirlingtools_hostname: "stirlingtools"

# specs
stirlingtools_memory: 1g

stirlingtools_container_name: stirlingtools
